defaults:
  device: "cuda"
  seed: 42
  train_size: 10000
  test_size: 1000
  targeted_data_size: 1000
  batch_size: 64
  byzantine_steps: 250
  byzantine_lr: 0.01
  aggregation_method: "mean"
  aggregator_optim: "sgd"
  aggregator_scheduler: null
  adversarial_scheduler: null
  random_restarts: 1
  epochs: 100
  rounds_per_epoch: 10
  train_pct: 1.0
  source_label: 0
  target_label: 1
  dataset: "cifar"
  model_type: "ResNet20"
  poisoner: "1xp"
  attack_method: "trajectory_matching"

experiments:
  - num_honest_workers: 0
    num_byzantine_workers: 1
    controlled_subset_size: 1.0
    budget_ratio: 1.0

  - num_honest_workers: 0
    num_byzantine_workers: 1
    controlled_subset_size: 1.0
    budget_ratio: 0.25

  - num_honest_workers: 0
    num_byzantine_workers: 1
    controlled_subset_size: 0.25
    budget_ratio: 0.25

  - num_honest_workers: 2
    num_byzantine_workers: 1
    controlled_subset_size: 0.5
    budget_ratio: 0.5

  - num_honest_workers: 2
    num_byzantine_workers: 2
    controlled_subset_size: 1.0
    budget_ratio: 1.0


